In [1]:
import numpy as np

In [13]:
#dim: var, time, lat, lon

red = np.array([[11, 12,],
               [21, 22,],])

green = np.array([[18, 19,],
               [28, 29,],])

data = np.array([[red, red+1, red+2],
                [green, green+1, green+2]])

"""
data = np.array([[[  1.,  20.],
                    [  2.,  21.],
                    [  3.,  22.],
                    [  4.,  23.]],

                   [[  5.,  24.],
                    [  6.,  25.],
                    [  7.,  26.],
                    [  8.,  27.]],

                   [[  9.,  28.],
                    [ 10.,  29.],
                    [ 11.,  30.],
                    [ 12.,  31.]]])
"""
None

In [14]:
data

array([[[[11, 12],
         [21, 22]],

        [[12, 13],
         [22, 23]],

        [[13, 14],
         [23, 24]]],


       [[[18, 19],
         [28, 29]],

        [[19, 20],
         [29, 30]],

        [[20, 21],
         [30, 31]]]])

In [15]:
data.shape


(2, 3, 2, 2)

In [20]:
a = np.reshape(data, (2,3,-1), order='C').transpose((2,1,0))
print(a.shape)
a

(4, 3, 2)


array([[[11, 18],
        [12, 19],
        [13, 20]],

       [[12, 19],
        [13, 20],
        [14, 21]],

       [[21, 28],
        [22, 29],
        [23, 30]],

       [[22, 29],
        [23, 30],
        [24, 31]]])

In [19]:
a.tranpose(())

(4, 3, 2)

In [22]:
y = np.array([1,2,3,4])

In [24]:
lat_size = 2
np.reshape(y,(lat_size,-1))

array([[1, 2],
       [3, 4]])

In [8]:
data2D = data.transpose(2,0,1).reshape(-1,data.shape[1])
data2D

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.]])

In [9]:
data2D.shape


(6, 4)

In [10]:
data2D.reshape(np.roll(data.shape,1)).transpose(1,2,0)

array([[[ 1., 20.],
        [ 2., 21.],
        [ 3., 22.],
        [ 4., 23.]],

       [[ 5., 24.],
        [ 6., 25.],
        [ 7., 26.],
        [ 8., 27.]],

       [[ 9., 28.],
        [10., 29.],
        [11., 30.],
        [12., 31.]]])